# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib iucnrle, .registration = TRUE
NULL

#' Version of the underlying iucn-rle-core calculation engine.
#' @export
rle_version <- function() .Call(wrap__rle_version)

# nolint end
