# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib iucnrle, .registration = TRUE
NULL

#' Version of the underlying iucn-rle-core calculation engine.
#' @export
rle_version <- function() .Call(wrap__rle_version)

#' The IUCN threshold table as TOML.
#' @export
rle_thresholds_toml <- function() .Call(wrap__rle_thresholds_toml)

#' SHA-256 of the IUCN threshold table.
#' @export
rle_thresholds_sha256 <- function() .Call(wrap__rle_thresholds_sha256)

#' Assess IUCN RLE Criterion B, returning a JSON summary.
#'
#' Clauses arrive as two parallel character vectors so the interface stays a plain
#' R vector pair rather than a list of lists. Clause (c) is separate because it is a
#' count of threat-defined locations, not a status.
#' @export
rle_criterion_b_json <- function(eoo_km2, aoo_cells, clause_names, clause_statuses, locations, no_plausible_threats, locations_insufficient_information, eoo_lower_km2, eoo_upper_km2, aoo_lower_cells, aoo_upper_cells) .Call(wrap__rle_criterion_b_json, eoo_km2, aoo_cells, clause_names, clause_statuses, locations, no_plausible_threats, locations_insufficient_information, eoo_lower_km2, eoo_upper_km2, aoo_lower_cells, aoo_upper_cells)

#' Compute Criterion B spatial metrics from a distribution map, returning JSON.
#'
#' Polygons arrive as a JSON array rather than as nested R lists. Walking a deeply
#' nested SEXP structure across the FFI boundary would be far more code for no gain,
#' and jsonlite is already a dependency of the R wrapper.
#' @export
rle_distribution_metrics_json <- function(polygons_json) .Call(wrap__rle_distribution_metrics_json, polygons_json)

# nolint end
